# Generated by Django 3.0.7 on 2020-07-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30)),
                ('heroname', models.CharField(max_length=30)),
                ('heroinename', models.CharField(max_length=30)),
                ('diretor', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=300)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
    ]
