# Generated by Django 3.0.6 on 2020-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
